### PR TITLE
fix: sound of compressed video

### LINKED ISSUE #79: Video can't play after compression in android

### PR DESCRIPTION
**Pull request by nomi9995**
## Summary
fixed #79

## Changelog

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Comment by martsneld** [comment]
@nomi9995 I still get the same issue. This library is still compressing video without sound. I am using react-native-compressor@1.3.4. The latest one.

**Comment by nomi9995** [comment]
@martsneld can you attach video so i can reproduce same issue on my side?

**Comment by martsneld** [comment]
@nomi9995 https://drive.google.com/file/d/14AzEOUZvrj_EliV5KCSIQtHdDgUr6fGg/view?usp=sharing
Thank you for your quick response. Please let me know what the problem is. I am under the pressure because of timeline.

**Comment by nomi9995** [comment]
@martsneld i will see it after half an hour

**Comment by martsneld** [comment]
@nomi9995 Thank you

**Comment by nomi9995** [comment]
@martsneld it is working on my side. here is your compressed video

https://user-images.githubusercontent.com/36044436/151615207-e4c4f8f7-26ee-4a22-ad78-6f825b96529d.mp4




can you try this in `build.gradle`
```
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
```
it will clear cache.

**Comment by martsneld** [comment]
@nomi9995 Let me try.

**Comment by martsneld** [comment]
@nomi9995 Where should I add it? inside dependencies or android?

**Comment by nomi9995** [comment]
@martsneld https://stackoverflow.com/questions/30641661/gradle-how-can-i-specify-the-cacheresolutionstrategy-for-the-snapshot-version-in

**Comment by martsneld** [comment]
```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 30
        googlePlayServicesAuthVersion = "19.2.0"
    }
    repositories {
        google()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.1.0')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10"
        classpath 'com.google.gms:google-services:4.3.10'
    }
    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}
```
I added it, but it doesn't work. ;(

**Comment by nomi9995** [comment]
@martsneld can you connect with me on linkedin? https://numan.dev

**Comment by martsneld** [comment]
@nomi9995 My email is martsneldhome@gmail.com. Can you do g-meet?

**Comment by nomi9995** [comment]
@martsneld can you give me 20 minutes?. I have to fix one bug then we will see it on google meet.

**Comment by martsneld** [comment]
@nomi9995 Thank you

**Comment by nomi9995** [comment]
@martsneld can you check `1.4.0` version?

**Comment by martsneld** [comment]
@nomi9995 Thank you so much. I will check and let you know.

**Comment by nomi9995** [comment]
@martsneld sorry to hear this. i am unable to help you more util i get repro on my side. can you make a repro example and send it to me. if it reproduce it on my side then i can fix it. i am going to go to sleep. if you give me repro than i can fix it morning. thanks

**Comment by martsneld** [comment]
@nomi9995 Is react-native-ffmpeg required on sample project?

**Comment by nomi9995** [comment]
@martsneld ffmpeg is not required

**Comment by martsneld** [comment]
Can you add readme file for example project? I can't run it.

**Comment by nomi9995** [comment]
@martsneld sorry i am not at home. you can install node_modules by yarn install and run android from example project.

**Comment by martsneld** [comment]
> @martsneld it is working on my side. here is your compressed video
> 
> can you try this in `build.gradle`
> 
> ```
> configurations.all {
>     resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
> }
> ```
> 
> it will clear cache.

**Comment by martsneld** [comment]
> @martsneld it is working on my side. here is your compressed video
> 
>  6737d044-f55d-4de6-b436-3d290467dcd4.mp4 
> can you try this in `build.gradle`
> 
> ```
> configurations.all {
>     resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
> }
> ```
> 
> it will clear cache.

@nomi9995 please remove video.

**Comment by nomi9995** [comment]
@martsneld done

**Comment by martsneld** [comment]
@nomi9995 Thanks. I am preparing sample project.

**Comment by martsneld** [comment]
@nomi9995 This is a demo project.  https://github.com/martsneld/compress-demo.git

**Comment by nomi9995** [comment]
@martsneld it is working on my side. I just had to give manual storage permission for compression.

**Comment by nomi9995** [comment]
here is the code. now camera roll save is also working.
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React, {useRef} from 'react';

import {
  Button,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  useColorScheme,
  View,
} from 'react-native';
import * as ImagePicker from 'react-native-image-picker';
import {Video} from 'react-native-compressor';
import CameraRoll from '@react-native-community/cameraroll';

import {Colors, Header} from 'react-native/Libraries/NewAppScreen';

const App = () => {
  const cancellationIdRef = useRef<string>('');
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  const selectVideo = async () => {
    try {
      ImagePicker.launchImageLibrary(
        {
          mediaType: 'video',
        },
        async result => {
          if (result.didCancel) {
          } else if (result.errorCode) {
            Alert.alert('Failed selecting video');
          } else {
            if (result.assets) {
              const source = result.assets[0];
              let uri = source.uri;
              console.log('~~~original~~~: ', uri);
              try {
                const dstUrl = await Video.compress(
                  uri,
                  {
                    compressionMethod: 'auto',
                    minimumFileSizeForCompress: 0,
                    getCancellationId: cancellationId =>
                      (cancellationIdRef.current = cancellationId),
                  },
                  progress => {
                    console.log('Compression Progress: ', progress);
                  },
                );
                console.log({dstUrl}, 'compression result');

                await CameraRoll.save(dstUrl.replace('file://', ''), {
                  type: 'video',
                });
              } catch (error) {
                console.log('compression error', error);
              }
            }
          }
        },
      );
    } catch (error) {
      console.log('Failed to select video', error);
    }
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View>
          <Button onPress={selectVideo} title="Learn More" />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
  autoFocusBox: {
    position: 'absolute',
    height: 64,
    width: 64,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'white',
    opacity: 0.4,
  },
  facesContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    top: 0,
  },
  face: {
    padding: 10,
    borderWidth: 2,
    borderRadius: 2,
    position: 'absolute',
    borderColor: '#FFD700',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  faceText: {
    color: '#FFD700',
    fontWeight: 'bold',
    textAlign: 'center',
    margin: 10,
    backgroundColor: 'transparent',
  },
  text: {
    padding: 10,
    borderWidth: 2,
    borderRadius: 2,
    position: 'absolute',
    borderColor: '#F00',
    justifyContent: 'center',
  },
  textBlock: {
    color: '#F00',
    position: 'absolute',
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#000',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: '#ececec',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
```

**Comment by martsneld** [comment]
I get the error below.
```
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
```

**Comment by nomi9995** [comment]
@martsneld this is just warning due to. event emitter

**Comment by martsneld** [comment]
@nomi9995 Sorry. I got error `[Error: null]`

**Comment by nomi9995** [comment]
@martsneld i did not see this error before.  here is my log
```
 LOG  Running "demo" with {"rootTag":11}
 LOG  ~~~original~~~:  content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F36/ORIGINAL/NONE/432603516
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 LOG  Compression Progress:  0.09750597178936005
 LOG  Compression Progress:  0.19664901494979858
 LOG  Compression Progress:  0.2958526909351349
 LOG  Compression Progress:  0.39502522349357605
 LOG  Compression Progress:  0.499139666557312
 LOG  Compression Progress:  0.5983089804649353
 LOG  Compression Progress:  0.6974863409996033
 LOG  Compression Progress:  0.7966768741607666
 LOG  Compression Progress:  0.8958379626274109
 LOG  Compression Progress:  0.9950039386749268
 LOG  {"dstUrl": "file://data/user/0/com.demo/cache/dc6e5856-b019-4efe-8c6f-d560bd5c6def.mp4"} compression result
```

**Comment by martsneld** [comment]
@nomi9995 Thank you

**Comment by nomi9995** [comment]
@martsneld I think, You need to give storage permission first. and then try again.
image

I think you have a previous version cache issue. can you try to clear cache by
image

**Comment by martsneld** [comment]
@nomi9995 Yeah, it works. Thank you for your help.

**Comment by nomi9995** [comment]
@martsneld how did you finally fixed because @govind-v-natex having the same issue.

**Pull request merged**
