### PR TITLE
fix: native module not found error

### PR DESCRIPTION
**Pull request by NiklasLehnfeld**

### CODE REVIEW

**Comment by nomi9995** [comment]
@NiklasLehnfeld it is already working in the latest version. peer dependency will only give warning nothing else

**Comment by NiklasLehnfeld** [comment]
@nomi9995 We actually use the newest version and unfortunately it wasn't working. We had to install the dependency on our own to fix that error. But if you think this wouldn't resolve the issue you can close the PR.

**Comment by GrandPoohBear** [comment]
FWIW, I was about to open the exact same issue, and @NiklasLehnfeld beat me by like two hours 😝.  I solved it by explicitly referencing the necessary podspec for react-native-get-random-values in our Podfile, but if this approach works instead, it would be cleaner!

**Comment by nomi9995** [comment]
@NiklasLehnfeld peer dependency will just give a warning to the user for installing manually `react-native-get-random-values`.  if users do not install this will get a native module error. if you can add the reference in podspec then I will approve and merge this PR.
Thanks

**Comment by daschaa** [comment]
@nomi9995 I wanted to add the dependency to the podspec, but I have no experience in this and after some research I still have no success. Could you elaborate on how to do this? Or give a hint in how to do this? Would be greatly appreciated 🙌

**Comment by lamazzing** [comment]
@nomi9995 Any update on this PR? I confirm I'm also getting the error: native module not found error.
Thank you for your help

**Comment by NiklasLehnfeld** [comment]
@nomi9995 I investigated a little bit and added the changes. 
Unfortunately I am not a iOS specialist so I am not sure if this is the smartest solution. Because here everyone has to put `use_modular_headers!` in their `Podfile`. I added you as a collaborator. Feel free to make changes on the pull-request.

**Comment by nomi9995** [comment]
@NiklasLehnfeld thanks a lot bro for your investigating. I think js base UUID solution would be best. what do you think about #66 . if you think a native UUID solution would be best then I can revert that PR and merge this

**Comment by NiklasLehnfeld** [comment]
@nomi9995 Good solution! 👍

**Pull request closed without merging**
